services:
  dhcpd:
    image: dafydd2277/dhcpd:latest
    environment:
      DHCPD_PROTOCOL: ${i_dhcp_protocol}
    logging:
      driver: syslog
      options:
        tag: cnt-{{.Name}}
        syslog-address: ${s_syslog_connection_type}://${s_syslog_ip}:${i_syslog_port}
        syslog-facility: daemon
    network_mode: host
    volumes:
      - type: bind
        source: ./etc/dhcpd
        target: /data
    working_dir: /data
  bind:
    image: store/internetsystemsconsortium/bind9:9.16
    logging:
      driver: syslog
      options:
        tag: cnt-{{.Name}}
        syslog-address: ${s_syslog_connection_type}://${s_syslog_ip}:${i_syslog_port}
        syslog-facility: daemon
    network_mode: host
    volumes:
      - type: bind
        source: ./etc/bind
        target: /etc/bind
      - type: bind
        source: ./var/cache/bind
        target: /var/cache/bind
      - type: bind
        source: ./var/lib/bind
        target: /var/lib/bind

